
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'https://github.com/brainiacbuddy/devops/blob/master/hello.py'
    arguments: '5'
  displayName: 'Run a one-line script'
