
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'master/devops/hello.py'
    arguments: '5'
    workingDirectory: '$(System.DefaultWorkingDirectory)/master/devops/'
  displayName: 'Run a one-line script'
