
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '/home/vsts/work/1/s/master/devops/hello.py'
    arguments: '5'
  displayName: 'Run a one-line script'
